mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "8080:8080"
      - "8883:8883"
    volumes:
      - ./data/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data/pwfile.txt:/etc/mosquitto/pwfile
      - ./certs:/var/lib/mosquitto
    restart: always